alter table if exists compte drop constraint if exists FKl1mxjkoi0jta51yesvy0hyn8g;
drop table if exists client cascade;
drop table if exists compte cascade;
alter table if exists compte drop constraint if exists FKl1mxjkoi0jta51yesvy0hyn8g;
drop table if exists client cascade;
drop table if exists compte cascade;
alter table if exists compte drop constraint if exists FKl1mxjkoi0jta51yesvy0hyn8g;
drop table if exists client cascade;
drop table if exists compte cascade;
alter table if exists compte drop constraint if exists FKl1mxjkoi0jta51yesvy0hyn8g;
drop table if exists client cascade;
drop table if exists compte cascade;
alter table if exists compte drop constraint if exists FKl1mxjkoi0jta51yesvy0hyn8g;
drop table if exists client cascade;
drop table if exists compte cascade;
alter table if exists compte drop constraint if exists FKl1mxjkoi0jta51yesvy0hyn8g;
drop table if exists client cascade;
drop table if exists compte cascade;
alter table if exists compte drop constraint if exists FKl1mxjkoi0jta51yesvy0hyn8g;
drop table if exists client cascade;
drop table if exists compte cascade;
alter table if exists compte drop constraint if exists FKl1mxjkoi0jta51yesvy0hyn8g;
drop table if exists client cascade;
drop table if exists compte cascade;
alter table if exists compte drop constraint if exists FKl1mxjkoi0jta51yesvy0hyn8g;
drop table if exists client cascade;
drop table if exists compte cascade;
alter table if exists compte drop constraint if exists FKl1mxjkoi0jta51yesvy0hyn8g;
drop table if exists client cascade;
drop table if exists compte cascade;
